Product.create!(
  [
    {
      id: 1,
      name: 'ベイクドチーズケーキ',
      price: 220,
      genre_id: 1,
      is_active: true,
      description: 'どっしりとした濃厚な味わいが特徴です。',
      created_at: 1.day.ago,
    },
    {
      id: 2,
      name: 'スフレチーズケーキ',
      price: 150,
      genre_id: 1,
      is_active: true,
      description: '軽くてふんわりとした軽い食感のオーブンで蒸し焼きにして作るケーキです。',
      created_at: 1.month.ago,
    },
    {
      id: 3,
      name: 'レアチーズケーキ',
      price: 340,
      genre_id: 1,
      is_active: true,
      description: 'オーブンで焼かずにゼラチンや寒天などを使って固めた冷たいチーズケーキです。',
      created_at: 2.day.ago,
    },
    {
      id: 4,
      name: 'チョコレートケーキ',
      price: 300,
      genre_id: 2,
      is_active: true,
      description: 'スポンジ生地やクリームにチョコレートやココアパウダーを混ぜたケーキです。',
      created_at: 3.day.ago,
    },
    {
      id: 5,
      name: 'ガトーショコラ',
      price: 360,
      genre_id: 2,
      is_active: true,
      description: '外はさくっとしていて、中はしっとりとしたチョコレートのケーキです。',
      created_at: 2.week.ago,
    },
    {
      id: 6,
      name: 'ブラウニー',
      price: 360,
      genre_id: 2,
      is_active: true,
      description: 'ブラウニーは卵白をメレンゲにせず使うので、メレンゲを使用しているガトーショコラと比べて、濃厚でずっしりとした味を楽しめるチョコレートケーキです。',
      created_at: 1.week.ago,
    },
    {
      id: 7,
      name: 'ザッハトルテ',
      price: 360,
      genre_id: 2,
      is_active: true,
      description: '光沢感のあるザッハトルテは、チョコレート味のバターケーキにあんずのジャムを塗り、表面をチョコレートでコーティングしたチョコレートケーキです。',
      created_at: 3.day.ago,
    },
    {
      id: 8,
      name: 'ショートケーキ',
      price: 260,
      genre_id: 3,
      is_active: true,
      description: '誕生日にかかせない定番ケーキ。',
      created_at: 2.week.ago,
    },
    {
      id: 9,
      name: 'シフォンケーキ',
      price: 160,
      genre_id: 3,
      is_active: true,
      description: '乳製品は使わずサラダ油を使い、ふんわり軽い生地のケーキです。',
      created_at: 1.week.ago,
    },
    {
      id: 10,
      name: 'モンブラン',
      price: 360,
      genre_id: 3,
      is_active: true,
      description: 'スポンジ生地の上に生クリームをのせ、上から螺旋状にマロンクリームをあしらったケーキです。',
      created_at: 4.day.ago,
    },
    {
      id: 11,
      name: 'パウンドケーキ',
      price: 360,
      genre_id: 4,
      is_active: true,
      description: 'バターを主原料としてつかい、卵白をメレンゲにせずに焼いた基本のバターケーキです。',
      created_at: 2.week.ago,
    },
    {
      id: 12,
      name: 'マーブルケーキ',
      price: 250,
      genre_id: 4,
      is_active: true,
      description: 'プレーン生地と、チョコレートなどのフレーバー入りの生地を混ぜて焼いたケーキです。',
      created_at: 1.week.ago,
    },
    {
      id: 13,
      name: 'アップルパイ',
      price: 250,
      genre_id: 5,
      is_active: true,
      description: '生のリンゴをパイ生地にのせて焼き、シナモンやナツメグなどのスパイスをきかせています。',
      created_at: 1.week.ago,
    },
    {
      id: 14,
      name: 'ミルフィーユ',
      price: 200,
      genre_id: 5,
      is_active: true,
      description: 'パイ生地とクリームを重ねたケーキです。',
      created_at: 5.day.ago,
    },
    {
      id: 15,
      name: 'シュークリーム',
      price: 220,
      genre_id: 6,
      is_active: true,
      description: '丸く焼いたシュー皮の中にクリームを入れたものです。',
      created_at: 5.day.ago,
    },
    {
      id: 16,
      name: 'エクレア',
      price: 180,
      genre_id: 6,
      is_active: true,
      description: '細長く焼いたシュー皮にクリームをサンドし、チョコレートでコーティングしたお菓子です。',
      created_at: 5.day.ago,
    },
    {
      id: 17,
      name: 'フルーツタルト',
      price: 230,
      genre_id: 7,
      is_active: true,
      description: 'タルト生地の上にアーモンドクリームやカスタードクリームをのせ、苺やブルーベリーなどの色鮮やかなフルーツを飾ったケーキです。',
      created_at: 2.week.ago,
    },
    {
      id: 18,
      name: 'エッグタルト',
      price: 170,
      genre_id: 7,
      is_active: true,
      description: 'タルト生地の上にカスタードクリームを入れて焼いた、小さめのタルトです。',
      created_at: 2.week.ago,
    },
  ]
)